# Generated by Django 4.0.4 on 2022-04-14 15:14

from django.db import migrations
from django.contrib.auth.hashers import make_password
import requests


def prefill_pokemons(apps, schema_editor):
    Pokemon = apps.get_model("api", "Pokemon")
    CustomUser = apps.get_model("api", "CustomUser")

    user = CustomUser.objects.create(
        email="test@gmail.com", password=make_password("TestPassword123!!")
    )

    for id in range(51):
        r = requests.get(f"https://pokeapi.co/api/v2/pokemon/{id}/")
        if r.ok:
            pokemon = r.json()
            name = pokemon["name"]
            data = {
                "name": name,
                "height_cm": pokemon["height"] * 10,
                "weight_kg": pokemon["weight"] / 10,
                "type": (pokemon["types"][0]["type"]["name"]).upper(),
                "description": f"A pokemon named {name}",
                "discovered_by": user,
            }
            Pokemon.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(prefill_pokemons),
    ]
