# Generated by Django 4.0.4 on 2022-04-14 15:14

from django.db import migrations
from django.contrib.auth.hashers import make_password
import requests


def prefill_pokemons(apps, schema_editor):
    Pokemon = apps.get_model("api", "Pokemon")
    CustomUser = apps.get_model("api", "CustomUser")

    user = CustomUser.objects.create(
        email="ash@kanto.com", password=make_password("ILovePokemons!!1")
    )

    for id in range(51):
        r = requests.get(f"https://pokeapi.co/api/v2/pokemon/{id}/")
        if r.ok:
            # Parse fields
            pokemon = r.json()
            name = pokemon["name"]
            weight_kg = pokemon["weight"] / 10
            height_cm = pokemon["height"] * 10
            type = (pokemon["types"][0]["type"]["name"]).upper()
            description = f"A pokemon named {name}"

            # Store pokemon
            data = {
                "name": name,
                "height_cm": height_cm if height_cm > 0 else 1,
                "weight_kg": weight_kg if weight_kg > 0 else 1,
                "type": type,
                "description": description,
                "discovered_by": user,
            }
            Pokemon.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(prefill_pokemons),
    ]
